apiVersion: apps/v1
kind: Deployment
metadata:
  name: factoryops-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: factoryops-api
  template:
    metadata:
      labels:
        app: factoryops-api
    spec:
      containers:
        - name: api
          image: {{ .Values.image.api }}
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
